[project]
name = "wmca"
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = [
    "torch",
    "numpy",
    "wandb",
    "python-dotenv",
    "crafter>=1.8.3",
    "scipy>=1.17.1",
    "gymnasium[atari]>=1.3.0",
    "ale-py>=0.11.2",
]

[project.optional-dependencies]
cuda = ["triton"]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
